# List all fantasy teams in your auction draft here
- Local Florida Man
- Bob Loblaw
- Team 33
- Nelson Studs
- Belichick This
- Brett Favres Next Team
- New Yawk Mongos
- Fear the Beard
- David S. Pumpkins
- Part Deux
- K Factor
- Mustangs
- oh leh dew it
- Revenge With a Fifth
